/** Perguntas frequentes, nos dois idiomas. */

import type { Lang } from '@/features/i18n/lang';

export interface FaqItem {
  question: string;
  answer: string;
}

export interface FaqCopy {
  openAria: string;
  closeAria: string;
  openTip: string;
  title: string;
  subtitle: string;
  items: FaqItem[];
  moreLabel: string;
}

export const FAQ: Record<Lang, FaqCopy> = {
  pt: {
    openAria: 'Abrir as perguntas frequentes',
    closeAria: 'Fechar as perguntas frequentes',
    openTip: 'Dúvidas? Perguntas frequentes',
    title: 'Perguntas frequentes',
    subtitle: 'O que costuma ser perguntado antes de começar.',
    items: [
      {
        question: 'Minhas fotos são enviadas para algum servidor?',
        answer:
          'Não. Elas são abertas e lidas dentro do seu navegador, na sua máquina. Não há upload, não há conta e não há banco de dados: fechar a aba encerra tudo.',
      },
      {
        question: 'O Memento usa inteligência artificial?',
        answer:
          'Não. Nenhuma legenda, título ou narrativa é gerada pelo sistema. Ele lê a data, a hora e as coordenadas gravadas em cada arquivo, ordena as fotos e deixa o resto para você.',
      },
      {
        question: 'E as fotos sem data no EXIF?',
        answer:
          'Entram pela data de modificação do arquivo e recebem um selo na grade, para você conferir se a posição ficou certa e mover à mão se não ficou.',
      },
      {
        question: 'Que formatos de imagem funcionam?',
        answer:
          'JPEG, PNG, WebP, GIF e AVIF, até 80 MB por arquivo. HEIC do iPhone só abre se o próprio navegador souber decodificar — no Safari costuma funcionar; nos outros, converta para JPEG antes.',
      },
      {
        question: 'Como o álbum é baixado?',
        answer:
          'Como um PDF de páginas, na ordem e na composição que você montou — o mesmo arquivo serve para mandar para alguém, guardar ou imprimir.',
      },
      {
        question: 'Dá para salvar e voltar depois?',
        answer:
          'Ainda não. Nesta fase nada é persistido, então o álbum vive enquanto a aba estiver aberta: monte e baixe na mesma sessão. Contas e álbuns salvos estão previstos para a Fase 2.',
      },
      {
        question: 'Quantas fotos aguenta de uma vez?',
        answer:
          'Depende da memória do seu dispositivo, não de um limite nosso. Algumas centenas costumam ir bem em um computador; no celular, prefira lotes menores.',
      },
      {
        question: 'É de graça? Tem pegadinha?',
        answer:
          'De graça e sem cadastro. Rodando inteiro no navegador, não há custo de servidor para repassar — e o código é aberto, dá para conferir.',
      },
    ],
    moreLabel: 'Ainda com dúvida? Leia a página Sobre',
  },
  en: {
    openAria: 'Open the frequently asked questions',
    closeAria: 'Close the frequently asked questions',
    openTip: 'Questions? Read the FAQ',
    title: 'Frequently asked questions',
    subtitle: 'What people usually ask before starting.',
    items: [
      {
        question: 'Are my photos uploaded to a server?',
        answer:
          'No. They are opened and read inside your browser, on your machine. No upload, no account, no database: closing the tab ends everything.',
      },
      {
        question: 'Does Memento use artificial intelligence?',
        answer:
          'No. No caption, title or narrative is generated by the system. It reads the date, time and coordinates written into each file, sorts the photos and leaves the rest to you.',
      },
      {
        question: 'What about photos with no EXIF date?',
        answer:
          'They come in by file modification date and get a badge in the grid, so you can check whether the position looks right and move them by hand if it does not.',
      },
      {
        question: 'Which image formats work?',
        answer:
          'JPEG, PNG, WebP, GIF and AVIF, up to 80 MB per file. iPhone HEIC only opens if the browser itself can decode it — Safari usually can; elsewhere, convert to JPEG first.',
      },
      {
        question: 'How is the album downloaded?',
        answer:
          'As a paged PDF, in the order and composition you built — the same file works to send to someone, to keep or to print.',
      },
      {
        question: 'Can I save and come back later?',
        answer:
          'Not yet. Nothing is persisted in this phase, so the album lives while the tab is open: build and download in the same session. Accounts and saved albums are planned for Phase 2.',
      },
      {
        question: 'How many photos can it handle at once?',
        answer:
          'It depends on your device memory, not on a limit we set. A few hundred usually go fine on a computer; on a phone, prefer smaller batches.',
      },
      {
        question: 'Is it free? What is the catch?',
        answer:
          'Free and no sign-up. Running entirely in the browser, there is no server cost to pass on — and the code is open, so you can check.',
      },
    ],
    moreLabel: 'Still unsure? Read the About page',
  },
};
